FROM python:3-alpine
	where apline is zip file version
	docker size will be lesser

WORKDIR /service	
	where service is working directory we can keep it as any name

COPY requirements.txt .
	copy the file to docker

RUN pip install -r requirements.txt
	run the command

COPY . ./
	here first . represents the app folder in local
	here second . represents the app folder in docker
	copy all the corrent working directory to docker corrent working directory

EXPOSE 8082
	port

ENTRYPOINT [ "python3", "app.py" ]
	where the app. will start




How To ignore the virtual env pipfile ?
	add pipfile in .dockerignore file


How To convert docker file to docker image ?
	docker build -t hellopython:latest .

	where
		docker build:		This is the Docker command to build an image from a Dockerfile.
		-t hellopython:latest:	The -t (tag) option names and tags the resulting Docker image.

			for ex:
					Multiple Tagging : docker build -t myapp:1.0 -t myapp:stable .
					Default Tagging  : docker build -t myapp .

		hellopython: 		The name of the Docker image.
		latest: 		The tag assigned to this image, which is a label indicating the version of the image. "latest" is a common tag used to 						indicate the most recent version.
		. (dot): 		Specifies the build context, indicating that Docker should use the current directory (where the Dockerfile is located) to 					find the files needed to build the image.

	we can check it in the docker image ls


Now, i want to run the docker image

How To Run the docker image ?
	docker run  hellopython
	
	Here , If i run this i will get error because we didn't allocate any external port to the container
			8082 is default port

How To Run the docker image with port mapping?

	docker run -p 8082:8070 hellopython

then we can check

http://127.0.0.1:8082/

	
